### ISSUE TITLE
Do you hava a plan to support XCFramework?

### ISSUE THREAD

**Issue by muukii** [AppsFlyerSDK/segment-appsflyer-ios#43] opened 2020-12-10 05:07 UTC
Do you have a plan to support XCFramework?
Because we will need it to build an app for Simulator with Arm64.

Thank you.

**Comment by af-fess** [comment] 2020-12-10 08:10
hey, 
Maybe this conversation can help you: https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/143

**Comment by af-fess** [comment] 2020-12-10 08:11
Possible duplicate of https://github.com/AppsFlyerSDK/segment-appsflyer-ios/issues/30

**Closed by af-fess** 2020-12-10 08:11 UTC
Labels: duplicate

**Comment by muukii** [comment] 2020-12-10 08:38
Oh thanks!
